name: realestate_app
description: Sell & Rent Homes App (Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

flutter:
  uses-material-design: true
